name: EbooksBD
url: http://ebooksbd.github.io
description: Online Ebooks Free Download

permalink: /themes/:title/

gems: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']

includes: 
[ fbcomments: yes]
